"use client";

import { AlertTriangle, CalendarDays, ChevronLeft, ChevronRight, Filter, Pencil, Plus, Trash2, Users, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Shift = { id:string; employeeId:string; employeeName:string; avatar:string; branchId:string; branch:string; date:string; dayLabel:string; shiftId:string; shiftLabel:string; start:string; end:string; status:"SCHEDULED"|"LEAVE" };
type Employee = { id:string; name:string; avatar:string; branchId:string; branch:string };
const shiftOptions = [{id:"morning",label:"Ca sáng",start:"08:00",end:"17:00"},{id:"afternoon",label:"Ca chiều",start:"13:00",end:"22:00"},{id:"evening",label:"Ca tối",start:"14:00",end:"23:00"}];
const branches=[{id:"q1",name:"Chi nhánh Quận 1"},{id:"q3",name:"Chi nhánh Quận 3"},{id:"bt",name:"Chi nhánh Bình Thạnh"}];

function iso(d:Date){return d.toISOString().slice(0,10)}
function addDays(d:Date,n:number){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function mondayOfWeek(offset:number){const base=new Date("2026-10-05T00:00:00");return addDays(base,offset*7)}
function label(d:Date){return new Intl.DateTimeFormat("vi-VN",{weekday:"short",day:"2-digit",month:"2-digit"}).format(d).replace(".,","").replace("/", "/")}

export default function ShiftsPage(){
 const [items,setItems]=useState<Shift[]>([]); const [employees,setEmployees]=useState<Employee[]>([]); const [branch,setBranch]=useState("all"); const [week,setWeek]=useState(0); const [modal,setModal]=useState<"create"|"edit"|null>(null); const [selected,setSelected]=useState<Shift|null>(null); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const start=mondayOfWeek(week); const days=Array.from({length:7},(_,i)=>addDays(start,i)); const startDate=iso(days[0]); const endDate=iso(days[6]);
 const [form,setForm]=useState({employeeId:"",date:startDate,branchId:"q1",shiftId:"morning"});
 async function load(){const p=new URLSearchParams({start_date:startDate,end_date:endDate,branch_id:branch}); const [sr,er]=await Promise.all([fetch(`/api/shifts?${p}`,{cache:"no-store"}),fetch(`/api/employee-status`,{cache:"no-store"})]);setItems(await sr.json());const employeeResponse=await er.json();const es=Array.isArray(employeeResponse)?employeeResponse:(employeeResponse.data??[]);setEmployees(es.map((e:any)=>({id:e.id,name:e.name,avatar:e.avatar,branchId:e.branchId,branch:e.branch})).filter((e:Employee)=>branch==="all"||e.branchId===branch));}
 useEffect(()=>{void load()},[branch,week]);
 const employeeRows=useMemo(()=>employees,[employees]);
 const openCreate=(date:string, emp?:Employee)=>{setError("");setSelected(null);setForm({employeeId:emp?.id??employees[0]?.id??"",date,branchId:emp?.branchId??(branch==="all"?"q1":branch),shiftId:"morning"});setModal("create")};
 const openEdit=(shift:Shift)=>{setError("");setSelected(shift);setForm({employeeId:shift.employeeId,date:shift.date,branchId:shift.branchId,shiftId:shift.shiftId});setModal("edit")};
 async function submit(){setError("");setSaving(true);const url=modal==="edit"?`/api/shifts/${selected!.id}`:"/api/shifts";const method=modal==="edit"?"PATCH":"POST";const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify({employee_id:form.employeeId,date:form.date,branch_id:form.branchId,shift_id:form.shiftId})});const data=await r.json();setSaving(false);if(!r.ok){setError(data.error??"Không thể lưu ca.");return}setModal(null);setSelected(null);await load()}
 async function remove(){if(!selected)return;if(!confirm(`Xóa ca của ${selected.employeeName} ngày ${selected.dayLabel}?`))return;const r=await fetch(`/api/shifts/${selected.id}`,{method:"DELETE"});if(!r.ok){const d=await r.json();setError(d.error??"Không thể xóa ca.");return}setModal(null);setSelected(null);await load()}
 const visibleCount=items.length; const warning=visibleCount<6;
 return <div className="space-y-5">
  <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-slate-400">Nhân sự / SCRUM-33</p><h1 className="text-2xl font-bold tracking-tight">Chủ xem và xếp ca cho nhân viên</h1><p className="mt-1 text-xs text-slate-500">Xem lịch mọi chi nhánh, điều phối nhân lực và chỉnh ca đã công bố.</p></div><div className="flex items-center gap-2"><button onClick={()=>setWeek(w=>w-1)} className="rounded-lg border border-slate-200 bg-white p-2 hover:bg-slate-50"><ChevronLeft size={16}/></button><div className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-xs font-semibold">{week===0?"Tuần hiện tại":`${week>0?"Tuần sau ":"Tuần trước "}${Math.abs(week)}`}</div><button onClick={()=>setWeek(w=>w+1)} className="rounded-lg border border-slate-200 bg-white p-2 hover:bg-slate-50"><ChevronRight size={16}/></button></div></div>
  <div className="flex flex-wrap gap-2"><label className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs"><Filter size={14}/><select value={branch} onChange={e=>setBranch(e.target.value)} className="bg-transparent outline-none"><option value="all">Tất cả chi nhánh</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><div className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-500"><CalendarDays size={14}/>{startDate.split("-").reverse().join("/")} – {endDate.split("-").reverse().join("/")}</div></div>
  {warning&&<div className="flex items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-800"><AlertTriangle size={18}/><div><p className="text-sm font-semibold">Cảnh báo thiếu người</p><p className="text-xs">Lịch đang có ít nhân sự hơn số ca cần điều phối. Hãy kiểm tra và bổ sung ca.</p></div></div>}
  <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-4"><div><p className="font-semibold">Lịch phân ca</p><p className="text-xs text-slate-500">Số ca hiển thị: {visibleCount} · Click ô trống để thêm ca</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><Users size={14}/> Nhân sự</div></div>
   <div className="overflow-x-auto"><div className="min-w-[1120px]"><div className="grid grid-cols-[220px_repeat(7,1fr)] border-b border-slate-100 bg-slate-50 text-center text-[11px] font-semibold text-slate-500"><div className="border-r border-slate-100 px-2 py-3 text-left">Nhân viên</div>{days.map(d=><div key={iso(d)} className="border-r border-slate-100 px-2 py-3">{label(d)}</div>)}</div>
   <div className="divide-y divide-slate-100">{employeeRows.map(emp=><div key={emp.id} className="grid grid-cols-[220px_repeat(7,1fr)]"><div className="flex items-center gap-3 border-r border-slate-100 bg-white p-4"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-50 text-xs font-bold text-blue-700">{emp.avatar}</div><div><p className="text-sm font-semibold">{emp.name}</p><p className="text-[11px] text-slate-500">{emp.branch}</p></div></div>{days.map(day=>{const date=iso(day);const row=items.find(x=>x.employeeId===emp.id&&x.date===date);return <div key={date} className="border-r border-slate-100 p-2">{row?<button onClick={()=>openEdit(row)} className={`group relative min-h-[68px] w-full rounded-lg border p-3 text-left transition hover:border-blue-300 ${row.status==="LEAVE"?"border-slate-200 bg-slate-50":"border-blue-100 bg-blue-50/60"}`}><p className="text-xs font-semibold text-slate-800">{row.shiftLabel}</p>{row.start&&<p className="mt-1 text-[11px] text-slate-500">{row.start} – {row.end}</p>}<Pencil size={13} className="absolute right-2 top-2 text-slate-400 opacity-0 group-hover:opacity-100"/></button>:<button onClick={()=>openCreate(date,emp)} className="group flex min-h-[68px] w-full items-center justify-center rounded-lg border border-dashed border-slate-200 text-slate-300 hover:border-blue-300 hover:bg-blue-50 hover:text-blue-600"><Plus size={17}/><span className="ml-1 text-[11px] font-semibold opacity-0 group-hover:opacity-100">Thêm ca</span></button>}</div>})}</div>)}</div></div></div>
  </section>
  {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="font-bold text-slate-900">{modal==="create"?"Tạo ca mới":"Chỉnh sửa ca"}</h2><p className="mt-1 text-xs text-slate-500">{modal==="create"?"Tạo ca trực tiếp từ ô lịch đã chọn.":`Đang sửa ca của ${selected?.employeeName}.`}</p></div><button onClick={()=>{setModal(null);setError("")}}><X size={18} className="text-slate-400"/></button></div>
   <div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600">Nhân viên<select value={form.employeeId} onChange={e=>setForm(f=>({...f,employeeId:e.target.value}))} className="mt-1 w-full rounded-lg border border-slate-200 p-2.5 text-sm font-normal outline-none">{employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.branch}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Chi nhánh<select value={form.branchId} onChange={e=>setForm(f=>({...f,branchId:e.target.value}))} className="mt-1 w-full rounded-lg border border-slate-200 p-2.5 text-sm font-normal outline-none">{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Ngày<input type="date" value={form.date} onChange={e=>setForm(f=>({...f,date:e.target.value}))} className="mt-1 w-full rounded-lg border border-slate-200 p-2.5 text-sm font-normal outline-none"/></label><label className="text-xs font-semibold text-slate-600">Loại ca<select value={form.shiftId} onChange={e=>setForm(f=>({...f,shiftId:e.target.value}))} className="mt-1 w-full rounded-lg border border-slate-200 p-2.5 text-sm font-normal outline-none">{shiftOptions.map(s=><option key={s.id} value={s.id}>{s.label} ({s.start} – {s.end})</option>)}</select></label></div>
   {error&&<div className="mt-4 rounded-lg border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700">{error}</div>}
   <div className="mt-5 flex items-center justify-between gap-2">{modal==="edit"?<button onClick={()=>void remove()} className="inline-flex items-center gap-2 rounded-lg border border-rose-200 px-4 py-2 text-xs font-semibold text-rose-700 hover:bg-rose-50"><Trash2 size={14}/>Xóa ca</button>:<span/>}<div className="flex gap-2"><button onClick={()=>setModal(null)} className="rounded-lg border border-slate-200 px-4 py-2 text-xs font-semibold">Hủy</button><button disabled={saving} onClick={()=>void submit()} className="rounded-lg bg-[#0C66E4] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{saving?"Đang lưu...":modal==="create"?"Tạo ca":"Lưu thay đổi"}</button></div></div>
  </div></div>}
 </div>
}
